#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov  6 20:55:27 2022

@author: george
"""

import numpy as np
import pandas as pd

from tqdm import tqdm
import os, glob



def addLagDisplacementToDF(trackDF):
    distDF = pd.DataFrame()
    
    distDF['x1'] = trackDF['x'][:-1].to_numpy()
    distDF['x2'] = trackDF['x'][1:].to_numpy()
    distDF['y1']  = trackDF['y'][:-1].to_numpy()
    distDF['y2'] = trackDF['y'][1:].to_numpy()      
    distDF['track_number'] = trackDF['track_number'][:-1]
    distDF['track_number2'] = trackDF['track_number'][1:].to_numpy()
    
    #calculate lag Distance
    distDF['x2-x1_sqr'] = np.square(distDF['x2']-distDF['x1'])
    distDF['y2-y1_sqr'] = np.square(distDF['y2']-distDF['y1'])      
    distDF['distance'] = np.sqrt((distDF['x2-x1_sqr']+distDF['y2-y1_sqr']))
    
    #set final track position lags to Nan
    distDF['endValue'] = distDF['track_number'] - distDF['track_number2'] 
    distDF['mask'] = distDF['endValue'] != -1
    distDF['lag'] = distDF['distance'].where(distDF['mask'])
    
    #add lags to trackDF
    trackDF['lag'] = distDF['lag'] 

    #add track mean lag distance to all rows
    trackDF['meanLag'] = trackDF.groupby('track_number')['lag'].transform('mean')    

    #add 'radius_gyration' (scaled by mean lag displacement
    trackDF['radius_gyration_scaled'] = trackDF['radius_gyration']/trackDF['meanLag']
    
    return trackDF


def processTrackFiles(tracksList):
    for trackFile in tqdm(tracksList):
        #load into df
        trackDF = pd.read_csv(trackFile)
        #add lag and mean lag
        trackDF = addLagDisplacementToDF(trackDF)
        #replace file
        trackDF.to_csv(trackFile)
        

if __name__ == '__main__':
    ##### RUN ANALYSIS        
    path = '/Users/george/Data/10msExposure10s'
    
    #get folder paths
    tracksList = glob.glob(path + '/**/*_bin10_locs_tracksRG.csv', recursive = True)  
    
    #process files
    processTrackFiles(tracksList)
    

    
    

    
    
    
    
    
    
    
    

    