#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  7 17:48:04 2022

@author: george
"""

import numpy as np
import pandas as pd

from tqdm import tqdm
import os, glob

pixelSize = 0.108

def makeLagDF(exptFolder):
    trackDF_list = glob.glob(exptFolder + '/**/*_SVMPredicted.csv', recursive = True)  
    lagDF_all = pd.DataFrame()
    lagDF_SVM_1 = pd.DataFrame()    
    lagDF_SVM_2 = pd.DataFrame()
    lagDF_SVM_3 = pd.DataFrame()    
    
    #add lags to df
    for lagFile in tqdm(trackDF_list):
        tempDF = pd.read_csv(lagFile)
        colName = tempDF.iloc[0]['Experiment']
        
        #convert pixels to microns
        tempDF['lag'] = tempDF['lag'] * pixelSize
        
        #filter lags by SVM class
        lagDF_all[colName] = tempDF['lag']
        lagDF_SVM_1[colName] = tempDF['lag'][tempDF['SVMPredictedClass'] == 1]  
        lagDF_SVM_2[colName] = tempDF['lag'][tempDF['SVMPredictedClass'] == 2]  
        lagDF_SVM_3[colName] = tempDF['lag'][tempDF['SVMPredictedClass'] == 3]  


    #df squared
    lagSquaredDF_all = np.square(lagDF_all)
    lagSquaredDF_SVM_1 = np.square(lagDF_SVM_1)
    lagSquaredDF_SVM_2 = np.square(lagDF_SVM_2)
    lagSquaredDF_SVM_3 = np.square(lagDF_SVM_3)    
    
        
    #export lagDF savenames
    savename_all = os.path.join(exptFolder, '{}_lags_All.csv'.format(exptFolder.split('/')[-1]))
    savename_all_sq = os.path.join(exptFolder, '{}_lagsquared_All.csv'.format(exptFolder.split('/')[-1]))
    
    savename_SVM_1= os.path.join(exptFolder, '{}_lags_SVM_1.csv'.format(exptFolder.split('/')[-1]))
    savename_SVM_1_sq = os.path.join(exptFolder, '{}_lagsquared_SVM_1.csv'.format(exptFolder.split('/')[-1]))

    savename_SVM_2= os.path.join(exptFolder, '{}_lags_SVM_2.csv'.format(exptFolder.split('/')[-1]))
    savename_SVM_2_sq = os.path.join(exptFolder, '{}_lagsquared_SVM_2.csv'.format(exptFolder.split('/')[-1]))

    savename_SVM_3= os.path.join(exptFolder, '{}_lags_SVM_3.csv'.format(exptFolder.split('/')[-1]))
    savename_SVM_3_sq = os.path.join(exptFolder, '{}_lagsquared_SVM_3.csv'.format(exptFolder.split('/')[-1]))    
    
    #export
    lagDF_all.to_csv(savename_all, float_format='%.5f')
    print ('{} exported'.format(savename_all))    
    lagSquaredDF_all.to_csv(savename_all_sq, float_format='%.5f')
    print ('{} exported'.format(savename_all_sq))    

    lagDF_SVM_1.to_csv(savename_SVM_1, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_1))    
    lagSquaredDF_SVM_1.to_csv(savename_SVM_1_sq, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_1_sq)) 

    lagDF_SVM_2.to_csv(savename_SVM_2, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_2))    
    lagSquaredDF_SVM_2.to_csv(savename_SVM_2_sq, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_2_sq)) 

    lagDF_SVM_3.to_csv(savename_SVM_3, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_3))    
    lagSquaredDF_SVM_3.to_csv(savename_SVM_3_sq, float_format='%.5f')
    print ('{} exported'.format(savename_SVM_3_sq)) 
    


if __name__ == '__main__':
    ##### RUN ANALYSIS        
    path = '/Users/george/Data/10msExposure10s'
    
    #get expt folder list
    exptList = glob.glob(path + '/*', recursive = True)   

    for exptFolder in tqdm(exptList):
        makeLagDF(exptFolder)


