#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  7 17:48:04 2022

@author: george
"""

import numpy as np
import pandas as pd

from tqdm import tqdm
import os, glob

pixelSize = 0.108


def getStats(df):
    stats = df.agg(
        {
        'n_segments':['mean','std'],
        'radius_gyration':['mean','std'],
        'asymmetry':['mean','std'],
        'skewness':['mean','std'],
        'kurtosis':['mean','std'],
        'radius_gyration_scaled':['mean','std'],
        'track_intensity_mean':['mean','std'],
        'lag':['mean','std'], 'fracDimension':['mean','std'],
        'netDispl':['mean','std'],
        'Straight':['mean','std'],
        'SVMPredictedClass':['mean']
        }
        )
    
    exptName = df['Experiment'][0]
    
    #create df with mean values
    summaryDF_mean = stats.iloc[0].to_frame(name=exptName).T    
    summaryDF_mean = summaryDF_mean.rename(columns={
            'n_segments':'n_segments_mean',
            'radius_gyration':'radius_gyration_mean',
            'asymmetry':'asymmetry_mean',
            'skewness':'skewness_mean',
            'kurtosis':'kurtosis_mean',
            'radius_gyration_scaled':'radius_gyration_scaled_mean',
            'track_intensity_mean':'track_intensity_mean',
            'lag':'lag_mean',
            'fracDimension':'fracDimension_mean',
            'netDispl':'netDispl_mean',
            'Straight':'Straight_mean',
            'SVMPredictedClass': 'SVMPredictedClass'                
            })    
    
    #create df with std values
    summaryDF_std = stats.iloc[1].to_frame(name=exptName).T
    summaryDF_std = summaryDF_std.rename(columns={
            'n_segments':'n_segments_std',
            'radius_gyration':'radius_gyration_std',
            'asymmetry':'asymmetry_std',
            'skewness':'skewness_std',
            'kurtosis':'kurtosis_std',
            'radius_gyration_scaled':'radius_gyration_scaled_std',
            'track_intensity_mean':'track_intensity_std',
            'lag':'lag_std',
            'fracDimension':'fracDimension_std',
            'netDispl':'netDispl_std',
            'Straight':'Straight_std'              
            })  
    
    resultDF = pd.concat([summaryDF_mean,summaryDF_std], axis=1)
    resultDF['n_tracks'] = len(df)
    
    #set column order
    resultDF = resultDF[[
            'n_segments_mean',
            'n_segments_std',            
            'radius_gyration_mean',
            'radius_gyration_std',            
            'asymmetry_mean',
            'asymmetry_std',            
            'skewness_mean',
            'skewness_std',            
            'kurtosis_mean',
            'kurtosis_std',            
            'radius_gyration_scaled_mean',
            'radius_gyration_scaled_std',            
            'track_intensity_mean',
            'track_intensity_std',            
            'lag_mean',
            'lag_std',            
            'fracDimension_mean',
            'fracDimension_std',            
            'netDispl_mean',
            'netDispl_std',            
            'Straight_mean',
            'Straight_std',            
            'SVMPredictedClass'  
        
        ]]
    return resultDF

def compileTrackResults(exptFolder):
    trackDF_list = glob.glob(exptFolder + '/**/*_SVMPredicted.csv', recursive = True)  

    statsTable_SVM_1 = pd.DataFrame()
    statsTable_SVM_2 = pd.DataFrame()
    statsTable_SVM_3 = pd.DataFrame()
       
    #add lags to df
    for trackFile in tqdm(trackDF_list):
        tempDF = pd.read_csv(trackFile)
        experimentName = tempDF.iloc[0]['Experiment']
        tempDF = tempDF[['track_number','n_segments', 'radius_gyration', 'asymmetry', 'skewness', 'kurtosis','radius_gyration_scaled', 'track_intensity_mean', 'lag', 'meanLag', 'fracDimension', 'netDispl', 'Straight', 'SVMPredictedClass']]
        
        #filter by SVM class
        tempDF_SVM_1 = tempDF[tempDF['SVMPredictedClass'] == 1] 
        tempDF_SVM_2 = tempDF[tempDF['SVMPredictedClass'] == 2] 
        tempDF_SVM_3 = tempDF[tempDF['SVMPredictedClass'] == 3] 
        
        #get mean values for each track
        resultDF_SVM_1 = tempDF_SVM_1.groupby('track_number', as_index=False).mean()
        resultDF_SVM_2 = tempDF_SVM_2.groupby('track_number', as_index=False).mean()
        resultDF_SVM_3 = tempDF_SVM_3.groupby('track_number', as_index=False).mean()  
        
        resultDF_SVM_1['Experiment'] = experimentName
        resultDF_SVM_2['Experiment'] = experimentName
        resultDF_SVM_3['Experiment'] = experimentName
        
        #export track tables        
        resultDF_SVM_1.to_csv(trackFile.split('.csv')[0]+'_SVM_1_trackStats.csv')
        resultDF_SVM_2.to_csv(trackFile.split('.csv')[0]+'_SVM_2_trackStats.csv')
        resultDF_SVM_3.to_csv(trackFile.split('.csv')[0]+'_SVM_3_trackStats.csv')
        
        #stats for all tracks
        statsTable_SVM_1 = statsTable_SVM_1.append(getStats(resultDF_SVM_1))
        statsTable_SVM_2 = statsTable_SVM_2.append(getStats(resultDF_SVM_2))
        statsTable_SVM_3 = statsTable_SVM_3.append(getStats(resultDF_SVM_3))


    #export stats tables   
    exptType = exptFolder.split('/')[-1]
    statsTable_SVM_1.to_csv(os.path.join(exptFolder,exptType+'_SVM_1_trackStats.csv'))
    statsTable_SVM_2.to_csv(os.path.join(exptFolder,exptType+'_SVM_2_trackStats.csv'))      
    statsTable_SVM_3.to_csv(os.path.join(exptFolder,exptType+'_SVM_3_trackStats.csv'))    

    print('{} stats exported'.format(exptType))    
        

if __name__ == '__main__':
    ##### RUN ANALYSIS        
    path = '/Users/george/Data/10msExposure10s'
    
    #get expt folder list
    exptList = glob.glob(path + '/*', recursive = True)   

    for exptFolder in tqdm(exptList):
        compileTrackResults(exptFolder)


